import os

GOOGLE_KNOWLEDGE_API = os.getenv('NEWSAI_GOOGLE_KNOWLEDGE_API', '')
NYTIMES_SEMANTIC_API = os.getenv('NEWSAI_NYTIMES_SEMANTIC_API', '')
ELASTIC_USER = os.getenv('NEWSAI_ELASTIC_USER', '')
ELASTIC_PASSWORD = os.getenv('NEWSAI_ELASTIC_PASSWORD', '')
