# Stdlib imports
import os

DEBUG = bool(os.getenv('NEWSAI_KNOWLEDGE_DEBUG', False))
ALCHEMY_API = os.getenv('NEWSAI_ALCHEMY_API', '')
GOOGLE_KNOWLEDGE_API = os.getenv('NEWSAI_GOOGLE_KNOWLEDGE_API', '')
NYTIMES_SEMANTIC_API = os.getenv('NEWSAI_NYTIMES_SEMANTIC_API', '')
READABILITY_API = os.getenv('NEWSAI_READABILITY_API', '')
CONTEXT_API_USERNAME = os.environ.get('NEWSAI_CONTEXT_API_USERNAME', '')
CONTEXT_API_PASSWORD = os.environ.get('NEWSAI_CONTEXT_API_PASSWORD', '')

SENTRY_USER = '99f7cb4fd29148f783ef5300f867570d'
SENTRY_PASSWORD = 'dabc526c069241dd852cc2b756c2cd06'
SENTRY_APP_ID = '69539'

BASE_URL = 'https://internal.newsai.org/api'
