import os

KEYSPACE = 'knowledge1'
GOOGLE_KNOWLEDGE_API = os.getenv('NEWSAI_GOOGLE_KNOWLEDGE_API', '')
NYTIMES_SEMANTIC_API = os.getenv('NEWSAI_NYTIMES_SEMANTIC_API', '')
AWS_ACCESS_KEY = os.getenv('NEWSAI_AWS_ACCESS_KEY', '')
AWS_SECRET_KEY = os.getenv('NEWSAI_AWS_SECRET_KEY', '')
AWS_REGION = os.getenv('NEWSAI_AWS_REGION', '')
